-- 에디터
DROP TABLE NGNEWBIE;

-- 에디터
CREATE TABLE NGNEWBIE (
  NO     INT(11)      NOT NULL, -- 번호
  RANDSTR VARCHAR(6)   NULL,     -- 랜덤값
  CONFIG  VARCHAR(255) NULL,     -- CONFIG
  HTML    MEDIUMTEXT   NULL,     -- HTML
  JS      MEDIUMTEXT   NULL      -- JS
);

-- 에디터
ALTER TABLE NGNEWBIE
  ADD
    CONSTRAINT PK_EDITOR -- 에디터 기본키
    PRIMARY KEY (
      NO -- 번호
    );
    
ALTER TABLE `bitdb`.`ngnewbie` 
CHANGE COLUMN `NO` `NO` INT(11) NOT NULL AUTO_INCREMENT ;